vim.g.have_nerd_font = true
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.autoindent = true -- Keep identation from previous line
vim.opt.breakindent = true
vim.opt.conceallevel = 2
vim.opt.cursorline = true
vim.opt.expandtab = true -- Convert tabs to spaces
vim.opt.fileencoding = "utf-8"
vim.opt.fileformat = unix
vim.opt.ignorecase = true
vim.opt.inccommand = "split"
vim.opt.listchars = {
	tab = "» ",
	trail = "·",
	nbsp = "␣",
}
vim.opt.list = true
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.shiftwidth = 4
vim.opt.showmode = false
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.smarttab = true
vim.opt.softtabstop = 4
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 4
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 250
