[languages.Python]
tab_size = 4
formatter = "language_server"
format_on_save = "on"
enable_language_server = true
language_servers = ["pylsp"]
show_completions_on_input = true

[languages.Go]
tab_size = 4
formatter = "language_server"
format_on_save = "on"
enable_language_server = true
language_servers = ["gopls"]
show_completions_on_input = true

[completions]
lsp = true
words = "fallback"
lsp_fetch_timeout_ms = 1000
lsp_insert_mode = "replace_suffix"

[lsp.pylsp.settings.plugins.pycodestyle]
enabled = true
ignore = ["E501"]

# [lsp.gopls] 
# Add custom gopls config here if needed

